'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace RecepcionComp
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://recepcion.ws/", ConfigurationName:="RecepcionComp.RecepcionComprobante")>  _
    Public Interface RecepcionComprobante
        
        'CODEGEN: Generating message contract since element name key from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://recepcion.ws/RecepcionComprobante/validarComprobanteRequest", ReplyAction:="http://recepcion.ws/RecepcionComprobante/validarComprobanteResponse")>  _
        Function validarComprobante(ByVal request As RecepcionComp.validarComprobanteRequest) As RecepcionComp.validarComprobanteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://recepcion.ws/RecepcionComprobante/validarComprobanteRequest", ReplyAction:="http://recepcion.ws/RecepcionComprobante/validarComprobanteResponse")>  _
        Function validarComprobanteAsync(ByVal request As RecepcionComp.validarComprobanteRequest) As System.Threading.Tasks.Task(Of RecepcionComp.validarComprobanteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class validarComprobanteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="validarComprobante", [Namespace]:="http://recepcion.ws/", Order:=0)>  _
        Public Body As RecepcionComp.validarComprobanteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As RecepcionComp.validarComprobanteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class validarComprobanteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public key As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public value As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal key As String, ByVal value As String)
            MyBase.New
            Me.key = key
            Me.value = value
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class validarComprobanteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="validarComprobanteResponse", [Namespace]:="http://recepcion.ws/", Order:=0)>  _
        Public Body As RecepcionComp.validarComprobanteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As RecepcionComp.validarComprobanteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class validarComprobanteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RecepcionComprobanteChannel
        Inherits RecepcionComp.RecepcionComprobante, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RecepcionComprobanteClient
        Inherits System.ServiceModel.ClientBase(Of RecepcionComp.RecepcionComprobante)
        Implements RecepcionComp.RecepcionComprobante
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function RecepcionComp_RecepcionComprobante_validarComprobante(ByVal request As RecepcionComp.validarComprobanteRequest) As RecepcionComp.validarComprobanteResponse Implements RecepcionComp.RecepcionComprobante.validarComprobante
            Return MyBase.Channel.validarComprobante(request)
        End Function
        
        Public Function validarComprobante(ByVal key As String, ByVal value As String) As String
            Dim inValue As RecepcionComp.validarComprobanteRequest = New RecepcionComp.validarComprobanteRequest()
            inValue.Body = New RecepcionComp.validarComprobanteRequestBody()
            inValue.Body.key = key
            inValue.Body.value = value
            Dim retVal As RecepcionComp.validarComprobanteResponse = CType(Me,RecepcionComp.RecepcionComprobante).validarComprobante(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function RecepcionComp_RecepcionComprobante_validarComprobanteAsync(ByVal request As RecepcionComp.validarComprobanteRequest) As System.Threading.Tasks.Task(Of RecepcionComp.validarComprobanteResponse) Implements RecepcionComp.RecepcionComprobante.validarComprobanteAsync
            Return MyBase.Channel.validarComprobanteAsync(request)
        End Function
        
        Public Function validarComprobanteAsync(ByVal key As String, ByVal value As String) As System.Threading.Tasks.Task(Of RecepcionComp.validarComprobanteResponse)
            Dim inValue As RecepcionComp.validarComprobanteRequest = New RecepcionComp.validarComprobanteRequest()
            inValue.Body = New RecepcionComp.validarComprobanteRequestBody()
            inValue.Body.key = key
            inValue.Body.value = value
            Return CType(Me,RecepcionComp.RecepcionComprobante).validarComprobanteAsync(inValue)
        End Function
    End Class
End Namespace
